export const GET_ALL_CHARACTERS = "GET_ALL_CHARACTERS";
export const GET_ALL_CHARACTERS_BY_URL = "GET_ALL_CHARACTERS_BY_URL";
export const GET_ALL_CHARACTERS_ALIENS = "GET_ALL_CHARACTERS_ALIENS";
export const GET_ALL_CHARACTERS_HUMANS = "GET_ALL_CHARACTERS_HUMANS";
export const GET_PAGINATION = "GET_PAGINATION";
export const SET_PAGINATION = "SET_PAGINATION";
